version: '3'
services:
  base:
    container_name: base
    image: base
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - db
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./src:/app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - base

networks:
  base:
    name: base
